-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 18:28:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adTable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adTable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adTable` DEFAULT CHARACTER SET utf8 ;
USE `adTable` ;

-- -----------------------------------------------------
-- Table `adTable`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adTable`.`ad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ad_name` VARCHAR(200) NOT NULL,
  `ad_value` VARCHAR(1000) NOT NULL,
  `ad_first_photo` VARCHAR(100) NOT NULL,
  `ad_second_photo` VARCHAR(100) NULL,
  `ad_third_photo` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
